name: Debricked

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  debricked-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Debricked scan
        uses: debricked/actions@v3
        with:
          debricked-token: ${{ secrets.DEBRICKED_TOKEN }}
