name: DeBricked Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  debricked-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: debricked/actions@v3
        with:
          apiToken: ${{ secrets.DEBRICKED_TOKEN }}
